tunnel: 9df90c7f-63cf-4ac9-87f1-f615c0292e4d
credentials-file: C:\Users\tungd\.cloudflared\9df90c7f-63cf-4ac9-87f1-f615c0292e4d.json
protocol: quic

ingress:
  # Tên miền cũ
  - hostname: sarita.click
    service: http://localhost:3000
  - hostname: www.sarita.click
    service: http://localhost:3000

  # Tên miền mới (chanhthu.click)
  - hostname: chanhthu.click
    service: http://localhost:3000
  - hostname: www.chanhthu.click
    service: http://localhost:3000

  # Subdomain cho Supabase Local API
  - hostname: api.chanhthu.click
    service: http://localhost:64321
  - hostname: api.sarita.click
    service: http://localhost:64321

  - service: http_status:404
